steps:
  - id: 'Logando no docker'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=willlino --password=$$PASSWORD']
    secretEnv: ['PASSWORD']
 
  - id: 'Subir imagem para o dockerhub'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'son-k8s-go:latest']
  
  - id: "Rodando testes"
    name: 'mirror.gcr.io/library/golang'
    env: ['GO111MODULE=auto']
    dir: 'go/src'
    args: ['go', 'test', '-v']
    
  - id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
    dir: 'go'
    args: ['-f', 'docker-compose.yaml', 'up', '-d', '--build']
  
images: ["willlino/son-k8s-go:latest"]

secrets:
  - kmsKeyName: projects/gout-273114/locations/global/keyRings/dockerhub-password/cryptoKeys/dockerhub-password
    secretEnv:
      PASSWORD: CiQAneJzlu6a7izWpXPbCOd2mLmQLFr2B12hnVCG0OHf0Cy933USMwCHdWDvJqtrBAuC49mRtzkhSH2JrH9oSeGM+GcTGOJC/zD2xtNZ5zDSvVybVcoRTsCCDg==